### ISSUE TITLE
{path,dynamic}: Consider implementing the priority queue for A* and D* Lite without map[int]int

### ISSUE THREAD

**Issue by vladimir-ch** [gonum/graph#100]
... in a similar way to the priority queue example in the standard library.

**Comment by kortschak** [comment]
The change suggested is not possible for the current implementation of A* and changes necessary to make it possible involve making a working copy of the provided graph, so I don't think it is worth it. The D* Lite changes give modest performance improvements for the graph tested. It may be worth revisiting this with more complicated data.
