### ISSUE TITLE
go version: drop 1.3 support

### ISSUE THREAD

**Issue by kortschak** [gonum/graph#125]
A number of the routines in graph depend on golang.org/x/tools/container/intsets. This has recently just added asm code which means the build breaks on 1.3 because of the textflag.h issue.

Does anyone have any drastic objection to this? The alternative is to vendor a version of intsets with the hack we use elsewhere to keep 1.3 happy.

@gonum/developers

**Comment by sbinet** [comment]
no objection w/ dropping support for 1.3.
