### ISSUE TITLE
topo: replace ConnectedComponents implementation with union-find

### ISSUE THREAD

**Issue by kortschak** [gonum/graph#179]
We can do better with the performance of this function.

**Comment by tcharding** [comment]
I copied path/disjoint.go to topo/. Modified it to store the node in the disjointSetNode struct. Then I implemented `func (ds *disjointSet) connectedComponents() [][]graph.Node` and used it to implement ConnectedComponents in topo. I ran benchmarks on the original implementation and the union-find implementation and the union-find was slower. Are you interested in seeing the code, or have you any further suggestions? No rush. See to it, if you choose to, at your leisure. Thanks.

**Comment by kortschak** [comment]
Closed after investigation in #190.
