### ISSUE TITLE
graph/simple: directed acyclic graph

### ISSUE THREAD

**Issue by liggitt** [gonum/graph#201]
A space-efficient directed acyclic graph implementation would be very welcome.

I have an implementation of a DAG on top of the simple.Undirected implementation, with `From` and `To` implementations that filter the edges returned based on whether they were from or to the specified node. In benchmarks of large graphs, it resulted in ~30% memory savings over the `simple.Directed` impl, since it didn't have to double-track edges.

**Comment by kortschak** [comment]
Please send a PR so that we can see what you are doing. Note that the design of the graph packages is such that there is no reason other than convenience to use the simple package provided graphs.

**Comment by kortschak** [comment]
@liggitt If you are still interested in adding this, please send the PR to gonum/gonum.

This is an issue clean-up for the deprecation of this repo.
