### ISSUE TITLE
all: semantics of head and tail are reversed cf. the rest of the world

### ISSUE THREAD

**Issue by kortschak** [gonum/graph#51]
I just noticed this today. From what I can see (this is not specified in the interface definition), graph.Edge.Head() returns the node at the non-pointy end of an edge, while graph.Edge.Tail() returns the node at the pointy end.

This is demonstrated, by the following:

```
package main

import (
	"fmt"

	"github.com/gonum/graph/concrete"
)

func main() {
	g := concrete.NewDirectedGraph()
	g.AddNode(concrete.Node(0))
	g.AddNode(concrete.Node(1))
	g.AddNode(concrete.Node(2))

	g.AddDirectedEdge(concrete.Edge{H: concrete.Node(0), T: concrete.Node(1)}, 0)
	g.AddDirectedEdge(concrete.Edge{H: concrete.Node(0), T: concrete.Node(2)}, 0)

	fmt.Println(g.Successors(concrete.Node(0)))
}
```

outputs:

```
[1 2]
```

This is the reverse of the normal interpretation.

>An arc e = (x, y) is considered to be directed from x to y; y is called the head and x is called the tail of the arc; y is said to be a direct successor of x, and x is said to be a direct predecessor of y.

I propose that we use simpler completely unambiguous terminology: `From` (conventionally tail) and `To` (conventionally head).

**Comment by vladimir-ch** [comment]
The above example seems to be a consequence of how `concrete.DirectedGraph.AddDirectedEdge()` is implemented. But the same behavior (edge direction reversed to the usual one) is suggested also by the docs for `graph.DirectedGraph.EdgeTo()`.

By a coincidence, `From`/`To` terminology is what I am used to, so as for me, I would welcome this change.

**Comment by kortschak** [comment]
I agree, it's internally consistent (and matches how I often read head/tail), but the reduction in ambiguity would be a bonus.

**Comment by kortschak** [comment]
I would like to change Graph.Successor and Graph.Predecessor to Graph.From (successors are reachable from) and Graph.To (predecessor can lead to) respectively as well (this is in line with the gonum and Go conventions of using non-Latinate language as much as possible).
