### ISSUE TITLE
search: BronKerbosch gives sporadic failures on go tip

### ISSUE THREAD

**Issue by kortschak** [gonum/graph#61]
I have been seeing sporadic failures of the BronKerbosch tests in the tip build of the matrix. The most recent was with go devel https://github.com/golang/go/commit/0b9866fd561d5ecebee14d73c0a4938dec5abe7d. I never see this with 1.4.2 or 1.3.3 (have run ~100 continuous tests on 1.4.2 without failure).

I am not yet sure whether this is a problem with BronKerbosch or something that is wrong with the new runtime. Do we wait for 1.5 to be released and then hit this hard, or try to exclude the possibility of error in BronKerbosch now?

Thoughts?

**Comment by Jragonmiris** [comment]
I'd rule out an error now, because if it's an error with the runtime it'd
probably be best if we could report it before 1.5 hits.

**Comment by kortschak** [comment]
Yeah. That was my thinking. Just building a tip here to play with.
