### ISSUE TITLE
internal: consider using Reflect instead of unsafe for fast path set comparison

### ISSUE THREAD

**Issue by kortschak** [gonum/graph#89]
@btracey raised this in https://github.com/gonum/graph/pull/85#discussion_r33307434.

**Comment by kortschak** [comment]
Here is a first data point for comparison using the reflect code compared to unsafe:

```
name          old time/op  new time/op  delta
BronKerbosch   392µs ± 1%   410µs ± 1%  +4.69%  (p=0.000 n=16+17)
```

In topo:

```
var res [][]graph.Node

func BenchmarkBronKerbosch(b *testing.B) {
	g := concrete.NewGraph()
	for u, e := range batageljZaversnikGraph {
		// Add nodes that are not defined by an edge.
		if !g.Has(concrete.Node(u)) {
			g.AddNode(concrete.Node(u))
		}
		for v := range e {
			g.SetEdge(concrete.Edge{F: concrete.Node(u), T: concrete.Node(v)}, 0)
		}
	}
	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		res = topo.BronKerbosch(g)
	}
}
```

I guess the question is what does dropping the unsafe get us (the reflect code is pretty much identical except for some dynamic checks that we don't need because we know statically what we have here).

The main benefit I can see is that with the reflect code internal.Set can be compiled in gae and other places where unsafe is banned.

**Comment by btracey** [comment]
That difference does not seem significant to me, especially since the case itself is a fast path for an otherwise costly operation. The Go team decided that similar speed reductions were okay for encoding/gob. I think we should follow their example and avoid unsafe.

**Comment by kortschak** [comment]
I'll try running a real world example (I have this at the moment for work) and report back.

**Comment by kortschak** [comment]
With unsafe my small real-world case gives `7441.04u 153.10s 2060.51r 137008kB` and the same with reflect gives `7608.83u 160.09s 2106.69r 136912kB` - ~2% impact. This code is mixed and the clique finding is only a minor component, code that is more involved in that work (social graph analysis for example) would see a hit closer to the 5% I see in the benchmark above.

It's not really reasonable to compare encoding/gob with this case for at least a couple of reasons:

1. encoding/gob is rarely going to be in a hot loop, whereas the main use of internal.Same is.
2. the use of unsafe in encoding/gob was fairly widespread, being intertwined into all the machines in a way that was involved in data mutation, whereas we have one use on one line that is trivial to inspect and understand and is not involved in data mutation directly.

A more realistic comparison would be math.Float64bits and math.Float64frombits which still do use unsafe.

I'm not convinced by the argument that because 5% is OK for encoding/gob it is OK for something that uses unsafe more simply and in hotter code. I would be convinced if we saw a need to have the code running on platforms that needed exclusion of unsafe. At the moment that is gae, so we could make Same be conditionally compiled to use unsafe or reflect on the basis of the appengine build tag.

On related not, Same doesn't need to be exported. So if/when this change happens it should be unexported. This was my mistake.
